# -*- coding: utf-8 -*-
"""Discussion Points

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJFThECU78Wfr9GKIOePZt8FHpB83yuv
"""

1.discount=0 is safe because integers are immutable.
cart=[] is dangerous because lists are mutable and shared between calls.

2.Rebinding means assigning a variable to a new object.
Mutating means changing the existing object itself.

3.Mutable: list, dict, set
Immutable: tuple, str, int

4.Yes, changes reflect outside because lists are mutable
and functions receive references to the same object.