# -*- coding: utf-8 -*-
"""q3_shopping_cart.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jfcoshuUf3JQeLKWFZ06g_Q7dEcqWPM
"""

def add_item(item, cart=[]):
    cart.append(item)
    return cart
print(add_item("apple"))
print(add_item("banana"))
print(add_item("milk", cart=["bread"]))
print(add_item("eggs"))
def add_item_fixed(item, cart=None):
    if cart is None:
        cart = []
    cart.append(item)
    return cart
print("\nFixed Function:")
print(add_item_fixed("apple"))
print(add_item_fixed("banana"))
def create_cart(owner, discount=0):
    return {
        "owner": owner,
        "items": [],
        "discount": discount
    }
def add_to_cart(cart, name, price, qty=1):
    item = {
        "name": name,
        "price": price,
        "qty": qty
    }
    cart["items"].append(item)
def update_price(price_tuple, new_price):
    try:
        price_tuple[1] = new_price
    except TypeError as e:
        print("Error:", e)
def calculate_total(cart):
    total = 0
    for item in cart["items"]:
        total += item["price"] * item["qty"]
    discount_amount = total * (cart["discount"] / 100)
    final_total = total - discount_amount
    return final_total
cart1 = create_cart("Aarav", 10)
cart2 = create_cart("Riya", 5)
add_to_cart(cart1, "Laptop", 50000, 1)
add_to_cart(cart1, "Mouse", 1000, 2)
add_to_cart(cart2, "Phone", 20000, 1)
add_to_cart(cart2, "Charger", 1500, 1)
print("\nCart 1:")
print(cart1)
print("\nCart 2:")
print(cart2)
print("\nCart 1 Total:", calculate_total(cart1))
print("Cart 2 Total:", calculate_total(cart2))
price_data = ("Laptop", 50000)
update_price(price_data, 60000)